name = "danish-weather"
main = ".open-next/worker.js"
compatibility_date = "2026-02-28"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "APPOINTMENTS"
id = "5504360ea1564b2aa1736e01c91eb4c1"
